[product model] creando modelo de productos
miguelbel00/p-grupal pull request #16
Opened 2022-11-08 22:32 UTC by nestornovella

DESCRIPTION
se creo el modelo de productos...

2022-11-08 23:11 UTC, agustinhummel approved these changes
ok

2022-11-09 12:14 UTC, miguelbel00 requested changes
remove MiguelFile.txt
let .env.example because this is necessary for the new members (in back)
unnecessary idCreator function can be replace for uuid and delete it
on src/models/products why is this folder here?

2022-11-09 12:14 UTC, miguelbel00 commented on api/database/models/index.js
> +console.log(sequelize.models)
delete console.log

2022-11-09 20:15 UTC, iSensative reviewed
Podrias eliminar la carpeta src ya que creo que no es necesaria por que estamos utilizando el metodo UUID que cumple la misma funcion que la function que se encuentra en "IdCreator"

2022-11-09 20:15 UTC, iSensative commented on api/database/models/index.js
> +console.log(sequelize.models)
Pienso lo mismo uwu

2022-11-09 23:13 UTC, closed without merging