[Reviews] creando modelo de reviews
miguelbel00/p-grupal pull request #17
Opened 2022-11-08 23:01 UTC by nestornovella

DESCRIPTION

se creo el modelo de reviews adjunto imagen de db...

2022-11-08 23:11 UTC, agustinhummel approved these changes
ok

2022-11-09 12:27 UTC, miguelbel00 requested changes
remove MiguelFile.txt
let .env.example because this is necessary for the new members (in back)
unnecessary idCreator function can be replace for uuid and delete it
on src/models/products why is this folder here?

2022-11-09 12:27 UTC, miguelbel00 commented on api/database/migrations/20221108225400-Create-Reviews.js
> +          defaultValue: idCreator()
changes for UUID

2022-11-09 20:17 UTC, iSensative approved these changes
All ok

2022-11-09 20:19 UTC, lucaaramos approved these changes
ok

2022-11-09 20:23 UTC, miguelbel00 requested changes
unnecessary folder src, could be delete

2022-11-09 20:23 UTC, miguelbel00 commented on api/database/migrations/20221108212203-create-Products.js
> +              type:DataTypes.STRING,
change DataTypes  for UUID

2022-11-09 20:23 UTC, miguelbel00 commented on api/database/migrations/20221108225400-Create-Reviews.js
> +          type:DataTypes.STRING,
Change DataType UUID

2022-11-09 20:26 UTC, gabicasas01 approved these changes

2022-11-09 23:13 UTC, closed without merging