feat(userCreate/B01) add controllers userCreate and Route
miguelbel00/p-grupal pull request #20
Opened 2022-11-09 14:58 UTC by FranzDuran

2022-11-09 20:32 UTC, iSensative approved these changes
All ok

2022-11-09 23:25 UTC, miguelbel00 requested changes
Peding evidence that the endpoint is working

2022-11-09 23:25 UTC, miguelbel00 commented on api/controllers/UserControllers/UserCreate.js
> +        message: 'Test retrieved successfully',
change the message for the apropiated

2022-11-10 03:57 UTC, miguelbel00 requested changes
Check when finish the trello card that the app is keep working
## ScreenShot
![imagen](https://user-images.githubusercontent.com/55055505/200997177-6a4c34b7-2706-4913-a1c6-b4d46be26aa0.png)

2022-11-10 03:57 UTC, miguelbel00 commented on api/controllers/UserControllers/UserCreate.js
> +const { endpointResponse } = require('../helpers/success')
This imports are working?

2022-11-10 13:52 UTC, miguelbel00 approved these changes
All Ok

2022-11-10 13:53 UTC, merged