[Home]:created Home
miguelbel00/p-grupal pull request #33
Opened 2022-11-10 13:31 UTC by lucaaramos

COMO: desarrollador
QUIERO: Crear home
PARA: mostrar 3 tarjetas de productos
![image](https://user-images.githubusercontent.com/69743118/201104698-d55531c7-ee4e-42f6-8857-c3b8e651bb41.png)

2022-11-10 15:59 UTC, Ariel-Alegre approved these changes
ok

2022-11-10 16:18 UTC, iSensative commented on client/public/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
Tener en cuenta que algunos integrantes usaron boostrap tambien , lo ideal seria que hagas un pull a la main y te traigas las lineas que los demas integrantes añaderon en este archivo

2022-11-10 16:19 UTC, iSensative commented on client/src/App.css
> -#root {
Eliminar por completo el archivo App.css

2022-11-10 16:21 UTC, iSensative commented on client/src/App.js
>        <Switch>
Mover la linea 11 a la linea 10

2022-11-10 16:21 UTC, miguelbel00 requested changes

2022-11-10 16:21 UTC, miguelbel00 commented on client/src/App.js
> +        <Route exact path='/'/><Home/>
this route is not inside the Switch?

2022-11-10 16:23 UTC, iSensative commented on client/src/componentes/home.jsx
> +import React from "react";
La carpeta 'componentes' tendria q ser eliminada ya que en el main tenemos la carpeta 'components'  y 'page' , tu archivo 'home.jsx' deberia estar en la carpeta de la main 'page' ya que es un componente principal .

2022-11-10 16:24 UTC, iSensative commented on client/src/index.css
> -:root {
Eliminar por completo el archivo 'index.css'

2022-11-10 16:26 UTC, iSensative commented on client/src/estilos/home.css
> +.header{
En MAIN tenemos 'styles' , mover tu archivo 'home.css'  a ese archivo

2022-11-10 22:23 UTC, iSensative approved these changes
Okaa

2022-11-11 02:19 UTC, miguelbel00 approved these changes
Ok

2022-11-11 02:19 UTC, agustinhummel approved these changes

2022-11-11 02:19 UTC, merged