[Models] change models relationships , migrations and seeds
miguelbel00/p-grupal pull request #47
Opened 2022-11-11 23:26 UTC by miguelbel00

Changes in relationships and fix errors, change seeds and models

2022-11-12 13:33 UTC, agustinhummel approved these changes
okok

2022-11-12 22:19 UTC, FranzDuran requested changes

2022-11-12 22:19 UTC, FranzDuran commented on api/.env.example
> +PORT=3009
deberias cambiar el puerto a 3005

2022-11-12 22:30 UTC, lucaaramos approved these changes
all ok

2022-11-12 22:32 UTC, gabicasas01 approved these changes

2022-11-12 22:38 UTC, Ariel-Alegre approved these changes

2022-11-13 00:33 UTC, FranzDuran approved these changes

2022-11-13 00:33 UTC, merged