[ordenamiento y filtrados , mejoras de codigo]
miguelbel00/p-grupal pull request #93
Opened 2022-11-21 19:57 UTC by nestornovella

description:

optimice y repare bugs en ordenamiento , cambie metodo de ordenamiento sort por quicksort que es mas eficaz, simplifique los ordenamientos por precio y mas vendidos a una sola accion , a un solo case en el reducer, quedando mas ordenado y funcional,

2022-11-21 20:57 UTC, agustinhummel approved these changes

2022-11-22 23:50 UTC, Ariel-Alegre approved these changes

2022-11-23 14:43 UTC, miguelbel00 requested changes
no es necesario hacer un archivo que contenga funciones, ya que se pueden poner facilmente en el mismo archivo del reducer, sin embargo se puede dejar tal como esta, queda a evaluacion de los compañeros,
Si pudieses subir una captura de como quedo el ordenamiento y de que funciona seria mejor

2022-11-23 14:43 UTC, miguelbel00 commented on client/src/functions/functions.js
> +export function orederOption(array, orderTipe) {
orederOption?

2022-11-23 14:47 UTC, FranzDuran approved these changes

2022-11-24 16:37 UTC, miguelbel00 commented on client/src/functions/functions.js
> +export function orederOption(array, orderTipe) {
Queda pendiete

2022-11-24 16:38 UTC, miguelbel00 approved these changes
Cambios pendiente

2022-11-24 23:09 UTC, merged

2022-11-24 23:10 UTC, lucaaramos reviewed
all ok