[Update data ] Ari/F28
miguelbel00/p-grupal pull request #94
Opened 2022-11-23 00:01 UTC by Ariel-Alegre

COMO usuario
QUIERO la opcion de editar mi perfil
PARA poder actualizar mis datos.

<img width="960" alt="Captura de pantalla_20221118_150655" src="https://user-images.githubusercontent.com/92393164/203444498-02617cf8-9111-4457-a969-04e8496af814.png">

###

<img width="960" alt="Captura de pantalla_20221122_204720" src="https://user-images.githubusercontent.com/92393164/203444632-95e1cc56-c368-43e5-99de-bd8b9c0fa9b3.png">

###

<img width="960" alt="Captura de pantalla_20221122_204749" src="https://user-images.githubusercontent.com/92393164/203444801-912e4802-7074-406e-a8f1-48c86541db70.png">

2022-11-23 14:49 UTC, FranzDuran approved these changes

2022-11-24 16:39 UTC, miguelbel00 commented on client/src/componets/EditProfile.jsx
> +        console.log(editUser);
quitar console.log

2022-11-24 23:11 UTC, miguelbel00 requested changes
el email no debe ser editable, simplemente se debe mostrar sin poder editar

2022-11-25 00:49 UTC, Ariel-Alegre commented on client/src/componets/EditProfile.jsx
> +        console.log(editUser);
resolved

2022-11-25 00:50 UTC, Ariel-Alegre commented
resolved

2022-11-25 23:28 UTC, merged